REMOVED = {
    'BVADecisions-bva_decisions_qa', # <16 examples
    'CABarExamEssays-MainSubset', # <16 examples
    'CiviproQuestions-civipro_questions_generate_from_passage', # <16 examples
    'CiviproQuestions-civipro_questions_generate_no_passage', # <16 examples
    'CiviproQuestions-civipro_questions_no_explanation', # <16 examples
    'EdgarNER-MainSubset', # NER
    'Ell18GreekNER-MainSubset', # NER
    'Ell4GreekNER-MainSubset', # NER
    'GermanLER-coarse', # NER
    'GermanLER-fine', # NER
    'IndianNER-MainSubset', # NER
    'LEXTREME-greek_legal_ner', # NER
    'LEXTREME-legalnero', # NER 
    'LEXTREME-lener_br', # NER
    'LEXTREME-mapa_coarse', # NER
    'LEXTREME-mapa_fine', # NER
    'MBE-mbe_subject', # Not released
    'MBE-mbe_subject_generation', # Not released
    # MiningLegalArguments is in all training lists, even though it is NER
    'MiningLegalArguments-agent', # NER
    'MiningLegalArguments-argType', # NER
    'SaraProlog-sara_prolog_statute', # <16 examples
    'SwissCourtViewGeneration-swiss_judgment_court_view_generation_lower_court', # <16 examples
}

ALL = {
    'BVADecisions-bva_decisions_label',
    'BVADecisions-bva_decisions_qa',
    'BrCAD5-brcad5_judgment',
    'BrCAD5-brcad5_law_area',
    'BrCAD5-brcad5_mc',
    'BrCAD5-brcad5_topic',
    'BrazilianBarExam-brazilian_bar_exam',
    'CABarExamEssays-MainSubset',
    'CAIL2019-cail_2019',
    'CAIL2022-cail_2022_crime',
    'CAIL2022-cail_2022_mc',
    'CAIL2022-cail_2022_response',
    'COLIEE-coliee_task3_generate_entailed_question',
    'COLIEE-coliee_task3_passage_entailment',
    'COLIEE-coliee_task4',
    'CaseBriefs-case_briefs',
    'ChangeMyView-change_my_view',
    'CiviproQuestions-civipro_questions_generate_from_passage',
    'CiviproQuestions-civipro_questions_generate_no_passage',
    'CiviproQuestions-civipro_questions_no_explanation',
    'ContractNLI-contract_nli',
    'EOIRPrivacy-eoir_privacy',
    'EdgarNER-MainSubset',
    'Ell18GreekNER-MainSubset',
    'Ell4GreekNER-MainSubset',
    'EurLexSum-bulgarian',
    'EurLexSum-croatian',
    'EurLexSum-czech',
    'EurLexSum-danish',
    'EurLexSum-dutch',
    'EurLexSum-english',
    'EurLexSum-estonian',
    'EurLexSum-finnish',
    'EurLexSum-french',
    'EurLexSum-german',
    'EurLexSum-greek',
    'EurLexSum-hungarian',
    'EurLexSum-irish',
    'EurLexSum-italian',
    'EurLexSum-latvian',
    'EurLexSum-lithuanian',
    'EurLexSum-maltese',
    'EurLexSum-polish',
    'EurLexSum-portuguese',
    'EurLexSum-romanian',
    'EurLexSum-slovak',
    'EurLexSum-slovenian',
    'EurLexSum-spanish',
    'EurLexSum-swedish',
    'GermanLER-coarse',
    'GermanLER-fine',
    'GermanRentalAgreements-german_rental_agreements',
    'ILDC-ildc',
    'IndianNER-MainSubset',
    # IndianTextSegmentation removed from RES training list, even though it is not NER
    'IndianTextSegmentation-indian_text_segmentation',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_acq',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_loss',
    'JECQA-jec_qa',
    'KoreanLegalQA-korean_legal_qa',
    'LEXTREME-brazilian_court_decisions_judgment',
    'LEXTREME-brazilian_court_decisions_unanimity',
    'LEXTREME-covid19_emergency_event',
    'LEXTREME-german_argument_mining',
    'LEXTREME-greek_legal_code_chapter',
    'LEXTREME-greek_legal_code_subject',
    'LEXTREME-greek_legal_code_volume',
    'LEXTREME-greek_legal_ner',
    'LEXTREME-legalnero',
    'LEXTREME-lener_br',
    'LEXTREME-mapa_coarse',
    'LEXTREME-mapa_fine',
    'LEXTREME-multi_eurlex_level_1',
    'LEXTREME-multi_eurlex_level_2',
    'LEXTREME-multi_eurlex_level_3',
    'LEXTREME-online_terms_of_service_clause_topics',
    'LEXTREME-online_terms_of_service_unfairness_levels',
    'LEXTREME-swiss_judgment_prediction',
    'LawngNli-lawng_nli_entailment',
    'LboxOpen-lbox_open_judgment',
    'LboxOpen-lbox_open_statute',
    'LegalCaseDocumentSummarization-legal_case_summarization_india',
    'LegalCaseDocumentSummarization-legal_case_summarization_uk',
    'LegalQA-legal_qa',
    'LexGLUE-case_hold',
    'LexGLUE-ecthr_a',
    'LexGLUE-ecthr_b',
    'LexGLUE-eurlex',
    'LexGLUE-ledgar',
    'LexGLUE-scotus',
    'LexGLUE-unfair_tos',
    'Littleton-littleton_events',
    'Littleton-littleton_graph',
    'MAUD-answer',
    'MAUD-category',
    'MAUD-question',
    'MAUD-text_type',
    'MBE-mbe_examples',
    'MBE-mbe_subject',
    'MBE-mbe_subject_generation',
    'MCExamsLaw-mc_exams_law_explain',
    'MCExamsLaw-mc_exams_law_no_explain',
    'MiningLegalArguments-agent',
    'MiningLegalArguments-argType',
    'MultiLexSum-long_to_short',
    'MultiLexSum-long_to_tiny',
    'MultiLexSum-short_to_tiny',
    'NaturalInstructionsLegal-billsum_summarization',
    'NaturalInstructionsLegal-cail2018_answer_generation',
    'NaturalInstructionsLegal-casehold_legal_answer_generation',
    'NaturalInstructionsLegal-casehold_legal_incorrect_answer_generation',
    'NaturalInstructionsLegal-cuad_answer_generation',
    'NaturalInstructionsLegal-cuad_question_generation',
    'NaturalInstructionsLegal-eurlex_classification',
    'NaturalInstructionsLegal-eurlex_summarization',
    'NaturalInstructionsLegal-online_privacy_policy_text_information_type_generation',
    'NaturalInstructionsLegal-online_privacy_policy_text_purpose_answer_generation',
    'NaturalInstructionsLegal-overruling_legal_classification',
    'OLCMemos-olc_memos',
    'PlainEnglishContractsSummarization-plain_english_contracts_summarization',
    'PrivacyQA-privacy_qa',
    'PrivacySummarization-privacy_summarization',
    'RedditLegalQA-reddit_legal_qa',
    'Sara-sara_entailment',
    'Sara-sara_tax_liability',
    'SaraProlog-sara_prolog_facts',
    'SaraProlog-sara_prolog_statute',
    'ShortAnswerFeedback-short_answer_feedback_error_class',
    'ShortAnswerFeedback-short_answer_feedback_openqa',
    'ShortAnswerFeedback-short_answer_feedback_rating',
    'SpanishLaborLaw-spanish_labor_law',
    'StackExchangeQuestionsLegal-stack_exchange_questions_legal',
    'SwissCourtViewGeneration-swiss_judgment_court_view_generation_lower_court',
    'SwissCourtViewGeneration-swiss_judgment_court_view_generation_same_court',
    'SwissCriticalityPrediction-swiss_judgment_criticality',
    'SwissJudgmentPrediction-swiss_judgment_multiple_choice',
    'SwissJudgmentPredictionXL-swiss_judgment_dismiss_approve',
    'SwissLawAreaPrediction-swiss_judgment_area_of_law_main_area',
    'SwissLawAreaPrediction-swiss_judgment_area_of_law_sub_area',
    'SwissLeadingDecisions-swiss_judgment_location',
    'SwissLegislation-swiss_legislation_abbreviation',
    'SwissLegislation-swiss_legislation_canton',
    'SwissLegislation-swiss_legislation_short',
    'SwissLegislation-swiss_legislation_title',
    'TsccAlqac-tscc_alqac_question_answering',
    'TurkishConstitutionalCourt-turkish_constitutional_multiple_choice',
    'TurkishConstitutionalCourt-turkish_constitutional_violation_no_violation',
    'USClassActions-us_class_actions_win_lose',
    'ValidWills-valid_wills_entailment',
}

ENGLISH = {
    'BVADecisions-bva_decisions_label',
    'BVADecisions-bva_decisions_qa',
    'CABarExamEssays-MainSubset',
    'CaseBriefs-case_briefs',
    'ChangeMyView-change_my_view',
    'CiviproQuestions-civipro_questions_generate_from_passage',
    'CiviproQuestions-civipro_questions_generate_no_passage',
    'CiviproQuestions-civipro_questions_no_explanation',
    # COLIEE is in ENGLISH training list, not in HF ENGLISH set, some is in Japanese
    'COLIEE-coliee_task3_generate_entailed_question',
    'COLIEE-coliee_task3_passage_entailment',
    'COLIEE-coliee_task4',
    'ContractNLI-contract_nli',
    'EdgarNER-MainSubset',
    'Ell18GreekNER-MainSubset',
    'Ell4GreekNER-MainSubset',
    'EOIRPrivacy-eoir_privacy',
    # EurLexSum English subset removed from ENGLISH training list
    # 'EurLexSum-english',
    'GermanLER-coarse',
    'GermanLER-fine',
    'ILDC-ildc',
    'IndianNER-MainSubset',
    'IndianTextSegmentation-indian_text_segmentation',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_acq',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_loss',
    'LawngNli-lawng_nli_entailment',
    'LegalCaseDocumentSummarization-legal_case_summarization_india',
    'LegalCaseDocumentSummarization-legal_case_summarization_uk',
    'LexGLUE-case_hold',
    'LexGLUE-ecthr_a',
    'LexGLUE-ecthr_b',
    'LexGLUE-eurlex',
    'LexGLUE-ledgar',
    'LexGLUE-scotus',
    'LexGLUE-unfair_tos',
    'Littleton-littleton_events',
    'Littleton-littleton_graph',
    'MAUD-answer',
    'MAUD-category',
    'MAUD-question',
    'MAUD-text_type',
    'MBE-mbe_examples',
    'MBE-mbe_subject',
    'MBE-mbe_subject_generation',
    'MCExamsLaw-mc_exams_law_explain',
    'MCExamsLaw-mc_exams_law_no_explain',
    'MiningLegalArguments-agent',
    'MiningLegalArguments-argType',
    'MultiLexSum-long_to_short',
    'MultiLexSum-long_to_tiny',
    'MultiLexSum-short_to_tiny',
    'NaturalInstructionsLegal-billsum_summarization',
    'NaturalInstructionsLegal-cail2018_answer_generation',
    'NaturalInstructionsLegal-casehold_legal_answer_generation',
    'NaturalInstructionsLegal-casehold_legal_incorrect_answer_generation',
    'NaturalInstructionsLegal-cuad_answer_generation',
    'NaturalInstructionsLegal-cuad_question_generation',
    'NaturalInstructionsLegal-eurlex_classification',
    'NaturalInstructionsLegal-eurlex_summarization',
    'NaturalInstructionsLegal-online_privacy_policy_text_information_type_generation',
    'NaturalInstructionsLegal-online_privacy_policy_text_purpose_answer_generation',
    'NaturalInstructionsLegal-overruling_legal_classification',
    'OLCMemos-olc_memos',
    'PlainEnglishContractsSummarization-plain_english_contracts_summarization',
    'PrivacyQA-privacy_qa',
    'PrivacySummarization-privacy_summarization',
    'RedditLegalQA-reddit_legal_qa',
    'Sara-sara_entailment',
    'Sara-sara_tax_liability',
    'SaraProlog-sara_prolog_facts',
    'SaraProlog-sara_prolog_statute',
    'StackExchangeQuestionsLegal-stack_exchange_questions_legal',
    'USClassActions-us_class_actions_win_lose',
    'ValidWills-valid_wills_entailment',
}

COMMERCIAL = {
    'BVADecisions-bva_decisions_label',
    'BVADecisions-bva_decisions_qa',
    'EurLexSum-bulgarian',
    'EurLexSum-croatian',
    'EurLexSum-czech',
    'EurLexSum-danish',
    'EurLexSum-dutch',
    'EurLexSum-english',
    'EurLexSum-estonian',
    'EurLexSum-finnish',
    'EurLexSum-french',
    'EurLexSum-german',
    'EurLexSum-greek',
    'EurLexSum-hungarian',
    'EurLexSum-irish',
    'EurLexSum-italian',
    'EurLexSum-latvian',
    'EurLexSum-lithuanian',
    'EurLexSum-maltese',
    'EurLexSum-polish',
    'EurLexSum-portuguese',
    'EurLexSum-romanian',
    'EurLexSum-slovak',
    'EurLexSum-slovenian',
    'EurLexSum-spanish',
    'EurLexSum-swedish',
    'GermanLER-coarse',
    'GermanLER-fine',
    'IndianNER-MainSubset',
    'IndianTextSegmentation-indian_text_segmentation',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_acq',
    'InternationalCitizenshipLawQuestions-international_citizenship_law_questions_mode_loss',
    'LawngNli-lawng_nli_entailment',
    'LegalCaseDocumentSummarization-legal_case_summarization_india',
    'LegalCaseDocumentSummarization-legal_case_summarization_uk',
    'LexGLUE-case_hold',
    'LexGLUE-ecthr_a',
    'LexGLUE-ecthr_b',
    'LexGLUE-eurlex',
    'LexGLUE-ledgar',
    'LexGLUE-scotus',
    'LexGLUE-unfair_tos',
    'LEXTREME-brazilian_court_decisions_judgment',
    'LEXTREME-brazilian_court_decisions_unanimity',
    'LEXTREME-covid19_emergency_event',
    'LEXTREME-german_argument_mining',
    'LEXTREME-greek_legal_code_chapter',
    'LEXTREME-greek_legal_code_subject',
    'LEXTREME-greek_legal_code_volume',
    'LEXTREME-greek_legal_ner',
    'LEXTREME-legalnero',
    'LEXTREME-lener_br',
    'LEXTREME-mapa_coarse',
    'LEXTREME-mapa_fine',
    'LEXTREME-multi_eurlex_level_1',
    'LEXTREME-multi_eurlex_level_2',
    'LEXTREME-multi_eurlex_level_3',
    'LEXTREME-online_terms_of_service_clause_topics',
    'LEXTREME-online_terms_of_service_unfairness_levels',
    'LEXTREME-swiss_judgment_prediction',
    'Littleton-littleton_events',
    'Littleton-littleton_graph',
    'MAUD-answer',
    'MAUD-category',
    'MAUD-question',
    'MAUD-text_type',
    'PrivacyQA-privacy_qa',
    'PrivacySummarization-privacy_summarization',
    'RedditLegalQA-reddit_legal_qa',
    'ShortAnswerFeedback-short_answer_feedback_error_class',
    'ShortAnswerFeedback-short_answer_feedback_openqa',
    'ShortAnswerFeedback-short_answer_feedback_rating',
    'SpanishLaborLaw-spanish_labor_law',
    'StackExchangeQuestionsLegal-stack_exchange_questions_legal',
    'SwissCourtViewGeneration-swiss_judgment_court_view_generation_lower_court',
    'SwissCourtViewGeneration-swiss_judgment_court_view_generation_same_court',
    'SwissCriticalityPrediction-swiss_judgment_criticality',
    'SwissJudgmentPrediction-swiss_judgment_multiple_choice',
    'SwissJudgmentPredictionXL-swiss_judgment_dismiss_approve',
    'SwissLawAreaPrediction-swiss_judgment_area_of_law_main_area',
    'SwissLawAreaPrediction-swiss_judgment_area_of_law_sub_area',
    'SwissLegislation-swiss_legislation_abbreviation',
    'SwissLegislation-swiss_legislation_canton',
    'SwissLegislation-swiss_legislation_short',
    'SwissLegislation-swiss_legislation_title',
    'TurkishConstitutionalCourt-turkish_constitutional_multiple_choice',
    'TurkishConstitutionalCourt-turkish_constitutional_violation_no_violation',
    'USClassActions-us_class_actions_win_lose',
}